/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoTempIOT;

import DWEET.ControllerDWEET;
import java.io.IOError;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.IIOException;
import lcd.ConexionArduino;

/**
 *
 * @author adria
 */
public class MonitorTemperatura extends javax.swing.JFrame {

    Hilo hilo;
    ConexionArduino ca = new ConexionArduino();

    /**
     * Creates new form MonitorTemperatura
     */
    public MonitorTemperatura() throws IOException {
        initComponents();
                    ca.conexion("COM4", 9600);
        hilo = new Hilo();
        hilo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTemperatura = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Fecha:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 40, -1, -1));

        jLabel2.setText("Hora:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));
        getContentPane().add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 90, 20));
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 80, 20));

        jLabel3.setText("Temperatura:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        lblTemperatura.setOpaque(true);
        lblTemperatura.setBackground(new java.awt.Color(204, 204, 204));
        lblTemperatura.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        lblTemperatura.setForeground(new java.awt.Color(102, 102, 102));
        lblTemperatura.setText("Nan");
        lblTemperatura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTemperatura.setAlignmentX(50);
        lblTemperatura.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 380, 170));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\adria\\Desktop\\H335018213a734d7298e39684fdeca167k.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setToolTipText("");
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 150));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1260, 1270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonitorTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonitorTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonitorTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonitorTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MonitorTemperatura().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MonitorTemperatura.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblTemperatura;
    // End of variables declaration//GEN-END:variables
    class Hilo extends Thread {

        ControllerDWEET cd = new ControllerDWEET();

        int contador = 0;

        @Override
        public void run() {
            while (true) {
                try {
                    Date date = new Date();
                    String fechaFormat = "dd/MM/yyyy", horaFormat = "hh:mm:ss";
                    String dato= ca.recibirDatos();
                    SimpleDateFormat newFecha = new SimpleDateFormat(fechaFormat);
                    SimpleDateFormat newHora = new SimpleDateFormat(horaFormat);

                    lblHora.setText(newHora.format(date));
                    lblFecha.setText(newFecha.format(date));
                    lblTemperatura.setText(dato);
                    cd.enviarNube(dato, "pruebas");
                    contador++;
                    ca.cerrarConexion();
                    Thread.sleep(1000);
                } catch (Exception e) {
                    System.out.println("Error");
                    e.printStackTrace();
                }
            }
        }
    }
}
